backend:
  name: github
  repo: TylerAPfledderer/tylerp-nuxt
publish_mode: editorial_workflow
media_folder: 'static/images' # Media files will be stored in the repo under images/uploads
public_folder: '/images'
collections:
  - name: 'projects'
    label: 'Projects'
    folder: 'content/projects'
    format: 'frontmatter'
    create: true
    preview_path: '/projects'
    fields: # The fields for each document, usually in front matter
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'projects',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Preview Image', name: 'previewImg', widget: 'image' }
      - { label: 'Link to Project Demo', name: 'demoUrl', widget: 'string' }
      - {
          label: 'Programming Tools Used',
          name: 'tags',
          widget: 'list',
          hint: 'Use only the following in lowercase: bootstrap, codepen, css, gatsby, html, js, linkedin, nuxt, react, sass, tailwindcss, twitter, vuejs',
        }
